### ISSUE TITLE
[Request] Add the ability to create effects

### ISSUE THREAD

**Issue by leonardoraele** [fedeAlterio/SignalsDotnet#1]
An "effect" is a function that depends on signals. It should run again whenever one of the signals it depends on changes value.

Example:

```csharp
Signal<int> stateA = new();
Signal<int> stateB = new();

Effect effect = new Effect(() => doSomethingWithStates(stateA.Value + stateB.Value));
```
```csharp
// later, once per update loop:
effect.Update();
```

In this example, the lambda function should be called once when the `Effect` is first instantiated, and again whenever `effect.Update()` is called after one of the states have been changed.

---

My use case for this feature is that I'm trying to use SignalsDotnet as a UI framework for Godot.

In this use case, I need to update a UI component whenever some state changes. Since the UI code is third party code, I can't change it to use DotnetSignals—instead, I have to be notified when the signals change and run a function that will do the actual UI update.

```csharp
Signal<int> itemCount = new();

Effect effect = new Effect(() => label.Text = $"Items count: {itemCount.Value}/{MAX_ITEM_CAPACITY}");
```

**Comment by fedeAlterio** [comment]
Hello!
Thank you for your interest. 
I was wondering what is the purpose of manually calling the update function.
Shouldn't the effect function be called every time the signal is changed? 
This is done in order to force the function to be invoked on the update loop?

**Comment by leonardoraele** [comment]
Sorry for the late response.

About the update function, my reasoning is that, this way, it prevents the effect from running multiple times if it depends on multiple signals and they change sequentially. In the example above, if `stateA` and `stateB` are changed one after the other, the effect would not run twice.

```csharp
stateA.Value = 4;
stateB.Value = 6;
effect.Update(); // Effect only runs once, here
```

But I see how this approach might be incovenient for applications that do not run in a loop. Maybe there's a better solution. Maybe something like below?

```csharp
// Runs a lambda function in a context that does not trigger effects until the lambda returns
Effect.AtomicOperation(() => {
    stateA.Value = 4;
    stateB.Value = 6;
});
```

**Comment by fedeAlterio** [comment]
I see what you mean.
The atomic operation seems really a good idea to me. Maybe we can also add an IScheduler parameter that schedules the effects to run on the main loop, what do you think?

```csharp
Effect.AtomicOperation(() => {
    stateA.Value = 4;
    stateB.Value = 6;
}, nextFrameScheduler);
```

**Comment by leonardoraele** [comment]
I'm not a fan of this approach because you need a reference to the scheduler anywhere where you need to update the signals.

I think it makes more sense to add the scheduler to the effect itself. In this way, atomic operations would not even be necessary.

Example:

```csharp
IScheduler scheduler = new ManualScheduler();
Effect effect = new Effect(() => doSomethingWithStates(stateA.Value + stateB.Value), scheduler);

// ...

// Then, run this once per frame in the game loop:
scheduler.Update(); // The effect will run here if any of it's dependencies changed.

// ...

// When the effect is no longer necessary:
effect.Dispose();
```

Atomic operations would still be necessary when using the default scheduler. (assuming the default scheduler runs the effect immediately upon a signal change)

**Comment by fedeAlterio** [comment]
@leonardoraele
You are right, thank you!
I've implemented it as you said. 
Take a look at #2.

**Comment by fedeAlterio** [comment]
I merged the PR, and updated the nuget package. https://www.nuget.org/packages/SignalsDotnet.
Thank you!
