### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by pisch** [fedeAlterio/SignalsDotnet#3]
Hi fedeAlterio,

Under what license would this package be available?

Regards,
pisch

**Comment by fedeAlterio** [comment]
Hi pisch.

Sorry for the delay. I see now that i do not have a license set up.
In these days I am trying to finish to develop[`ComputedAsync `and `EffectAsync` functionalities](https://github.com/fedeAlterio/SignalsDotnet/pull/4). When everything is ready I will also add a license file

It will be MIT

**Comment by fedeAlterio** [comment]
Added to the main branch
